### ISSUE TITLE
Add API reference documentation on the website

### ISSUE THREAD

**Issue by Affan-7** [karmada-io/website#472]
**What documentation would you like to be added**:
API documentation
Related to: karmada-io/karmada#3843

**Why do you think this document is needed**:
API reference documentation is helpful to understand the karmada APIs better.

**Where do you think the document should be placed**:
I think the document could be placed under /docs/reference/api-reference/<api group name>

- [x] Select a tool for generating docs ([bootprint](https://github.com/bootprint/bootprint))

- [x] Create a prototype of API docs (#471)

- [x] Fix the broken CSS

- [ ] Generate the splitted swagger json based on the API groups

- [ ] Generate the API docs based on the API groups

- [ ] Add API docs to the production

**Comment by RainbowMango** [comment]
Just looked at the bootprint, seems it has been moved to [bootprint-monorepo](https://github.com/bootprint/bootprint-monorepo), that's ok, but the concerning thing is it no activities since [Apr 11, 2020](https://github.com/bootprint/bootprint-monorepo/commit/8919c14e15362b4f2aa37565b8deb99dda7b57cb)
.
What do you think of it?

**Comment by XiShanYongYe-Chang** [comment]
Hi @Affan-7, it seems that we have finished this task, how about close this issue?

**Comment by Affan-7** [comment]
Oh I forgot to close this.

**Comment by XiShanYongYe-Chang** [comment]
Thanks, Affan~
