### ISSUE TITLE
Accessibility add links name to icons

### ISSUE THREAD

**Issue by Arhell** [karmada-io/website#495]
/assign
github icon

**Comment by RainbowMango** [comment]
Hi @Arhell Can you remind me which icon needs the link name?

**Comment by Arhell** [comment]
> Hi @Arhell Can you remind me which icon needs the link name?

![Screenshot_2](https://github.com/karmada-io/website/assets/26163841/a5f060b0-7def-4d4d-b435-817627c09219)
Here and https://github.com/karmada-io/website/pull/496

Corrected using the example of the main site https://docusaurus.io/

**Comment by RainbowMango** [comment]
Linked to some docs I just googled:
- What the `aria-label` is: https://www.w3.org/TR/wai-aria/#aria-label
- Why do I need aria-label and how should I use it?  https://stackoverflow.com/questions/22039910/what-is-aria-label-and-how-should-i-use-it

It makes sense to have the `aria-label` because it would help people(like, blind people) understand the button by using assistive technology. (Although I never received feedback that someone needs it yet)

My question is, is this the only place need to add the label?

**Comment by Arhell** [comment]
> Linked to some docs I just googled:
> 
> * What the `aria-label` is: https://www.w3.org/TR/wai-aria/#aria-label
> * Why do I need aria-label and how should I use it?  https://stackoverflow.com/questions/22039910/what-is-aria-label-and-how-should-i-use-it
> 
> It makes sense to have the `aria-label` because it would help people(like, blind people) understand the button by using assistive technology. (Although I never received feedback that someone needs it yet)
> 
> My question is, is this the only place need to add the label?

I understand you, I apologize for not giving a specific answer as you wrote, yes, only this place and if more icons are added there in the future, slack for example, then do the same.

**Comment by RainbowMango** [comment]
OK, that makes sense to me.
