### ISSUE TITLE
update website to docusaurus v3

### ISSUE THREAD

**Issue by Arhell** [karmada-io/website#544]
1. node version upgrade to v18 (update nerlify)
2. update docs style to fit.
I recommend updating by version
for example
https://github.com/karmada-io/website/tree/main/versioned_docs/version-v1.3 first PR
https://github.com/karmada-io/website/tree/main/versioned_docs/version-v1.4 second PR or other version
3. and at last,try to update docusaurus v3

/assign

**Comment by samzong** [comment]
I've successfully upgraded a Docusaurus site to version 3.0.1 (latest), and I'd like to share some issues I encountered along the way.

The good news is that all the information you need is available at: [Docusaurus v3 Migration Docs](https://docusaurus.io/zh-CN/docs/migration/v3).

One thing to note is that Docusaurus now parses all files with MDX by default. This means that even markdown files are treated as MDX, which can be problematic since code snippets in markdown files are parsed as JSX.

Changing this could be a huge task.

I used the following command to get an idea of how many files might be problematic, and it turns out there are about 126 markdown files that need to be revised.

```bash
npx docusaurus-mdx-checker

[ERROR] 126/1733 MDX files couldn't compile!
```

The main issues I came across were:

- Incorrect rendering of shorthand links: `<https://github.com/>` should be formatted as [Github](https://github.com/)
- Unescaped curly braces: `{POD_NAME}` should be escaped as `\{POD_NAME\}`

These issues are acknowledged in the Docusaurus blog post [Markdown and MDX improvements](https://docusaurus.io/blog/releases/3.0#markdown), with promises of future fixes. It might be worth waiting to see how these are resolved.

Additionally, I recommend integrating `docusaurus-mdx-checker` into Github CI pipeline to catch these issues automatically.

**Comment by RainbowMango** [comment]
Does the [Upgrading Dependencies](https://docusaurus.io/zh-CN/docs/migration/v3#upgrading-dependencies) is a good next step?

**Comment by Arhell** [comment]
> Does the [Upgrading Dependencies](https://docusaurus.io/zh-CN/docs/migration/v3#upgrading-dependencies) is a good next step?

No, first we need to prepare documentation for MDX v3.0, because without this there will be the errors that were here https://github.com/karmada-io/website/pull/510
